/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  docs: [
    {
      type: 'category',
      label: '1. แรงผลักดันการเปลี่ยนแปลง',
      items: [
        'driving-forces/factors',
        'driving-forces/implications',
      ]
    },
    {
      type: 'doc',
      id: 'intended-outcome',
    },
    {
      type: 'category',
      label: '3. นัยยะต่อนโยบาย',
      link: {
        type: 'doc',
        id: 'implications/overview',
      },
      items: [
        'implications/open-competition'
      ],
    }
  ],
   
};

module.exports = sidebars;
